//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_Kernel0;
int xdim1_Kernel0;


#undef OPS_ACC0
#undef OPS_ACC1


#define OPS_ACC0(x,y) (x+xdim0_Kernel0*(y))
#define OPS_ACC1(x,y) (x+xdim1_Kernel0*(y))

//user function
inline void Kernel0(const float * ut0, float * ut1)
{
  ut1[OPS_ACC1(0,0)] = ut0[OPS_ACC0(0,0)] + 2;
}

#undef OPS_ACC0
#undef OPS_ACC1



void Kernel0_c_wrapper(
  float *p_a0,
  float *p_a1,
  int x_size, int y_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1)
  #pragma acc loop
  #endif
  for ( int n_y=0; n_y<y_size; n_y++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_x=0; n_x<x_size; n_x++ ){
      Kernel0(  p_a0 + n_x*1*1 + n_y*xdim0_Kernel0*1*1,
           p_a1 + n_x*1*1 + n_y*xdim1_Kernel0*1*1 );

    }
  }
}
