//
// auto-generated by ops.py
//

int xdim0_Kernel0;
int xdim1_Kernel0;


#define OPS_ACC0(x,y) (n_x*1+n_y*xdim0_Kernel0*1+x+xdim0_Kernel0*(y))
#define OPS_ACC1(x,y) (n_x*1+n_y*xdim1_Kernel0*1+x+xdim1_Kernel0*(y))

//user function



void Kernel0_c_wrapper(
  const float * restrict ut0,
  float * restrict ut1,
  int x_size, int y_size) {
  #pragma omp parallel for
  for ( int n_y=0; n_y<y_size; n_y++ ){
    for ( int n_x=0; n_x<x_size; n_x++ ){
      
  ut1[OPS_ACC1(0,0)] = ut0[OPS_ACC0(0,0)] + 2;

    }
  }
}
#undef OPS_ACC0
#undef OPS_ACC1

